export const wordBankA = [
  { singular: "cat", plural: "cats" },
  { singular: "dog", plural: "dogs" },
  { singular: "student", plural: "students" },
  { singular: "car", plural: "cars" },
  { singular: "book", plural: "books" },
  { singular: "flower", plural: "flowers" },
  { singular: "bird", plural: "birds" },
  { singular: "apple", plural: "apples" },
  { singular: "teacher", plural: "teachers" },
  { singular: "computer", plural: "computers" },
  { singular: "child", plural: "children" },
  { singular: "doctor", plural: "doctors" },
  { singular: "tree", plural: "trees" },
  { singular: "house", plural: "houses" },
  { singular: "phone", plural: "phones" },
  { singular: "shoe", plural: "shoes" },
  { singular: "river", plural: "rivers" },
  { singular: "mountain", plural: "mountains" },
  { singular: "city", plural: "cities" },
  { singular: "country", plural: "countries" },
  { singular: "artist", plural: "artists" },
  { singular: "engineer", plural: "engineers" },
  { singular: "nurse", plural: "nurses" },
  { singular: "parent", plural: "parents" },
  { singular: "friend", plural: "friends" },
  { singular: "student", plural: "students" },
  { singular: "athlete", plural: "athletes" },
  { singular: "musician", plural: "musicians" },
  { singular: "actor", plural: "actors" },
  { singular: "writer", plural: "writers" },
  { singular: "bottle", plural: "bottles" },
  { singular: "cup", plural: "cups" },
  { singular: "plate", plural: "plates" },
  { singular: "fork", plural: "forks" },
  { singular: "spoon", plural: "spoons" },
  { singular: "window", plural: "windows" },
  { singular: "door", plural: "doors" },
  { singular: "table", plural: "tables" },
  { singular: "chair", plural: "chairs" },
  { singular: "lamp", plural: "lamps" },
  { singular: "pen", plural: "pens" },
  { singular: "pencil", plural: "pencils" },
  { singular: "notebook", plural: "notebooks" },
  { singular: "bag", plural: "bags" },
  { singular: "wallet", plural: "wallets" },
  { singular: "key", plural: "keys" },
  { singular: "clock", plural: "clocks" },
  { singular: "watch", plural: "watches" },
  { singular: "shirt", plural: "shirts" },
];

export const wordBankB = [
  { singular: "mammal", plural: "mammals" },
  { singular: "vehicle", plural: "vehicles" },
  { singular: "object", plural: "objects" },
  { singular: "fruit", plural: "fruits" },
  { singular: "device", plural: "devices" },
  { singular: "animal", plural: "animals" },
  { singular: "machine", plural: "machines" },
  { singular: "person", plural: "people" },
  { singular: "tool", plural: "tools" },
  { singular: "plant", plural: "plants" },
  { singular: "structure", plural: "structures" },
  { singular: "building", plural: "buildings" },
  { singular: "appliance", plural: "appliances" },
  { singular: "instrument", plural: "instruments" },
  { singular: "container", plural: "containers" },
  { singular: "utensil", plural: "utensils" },
  { singular: "furniture", plural: "furniture" },
  { singular: "material", plural: "materials" },
  { singular: "substance", plural: "substances" },
  { singular: "element", plural: "elements" },
  { singular: "organism", plural: "organisms" },
  { singular: "profession", plural: "professions" },
  { singular: "occupation", plural: "occupations" },
  { singular: "role", plural: "roles" },
  { singular: "title", plural: "titles" },
  { singular: "food", plural: "foods" },
  { singular: "drink", plural: "drinks" },
  { singular: "beverage", plural: "beverages" },
  { singular: "snack", plural: "snacks" },
  { singular: "dessert", plural: "desserts" },
  { singular: "game", plural: "games" },
  { singular: "sport", plural: "sports" },
  { singular: "activity", plural: "activities" },
  { singular: "event", plural: "events" },
  { singular: "festival", plural: "festivals" },
  { singular: "holiday", plural: "holidays" },
  { singular: "season", plural: "seasons" },
  { singular: "month", plural: "months" },
  { singular: "day", plural: "days" },
  { singular: "hour", plural: "hours" },
  { singular: "minute", plural: "minutes" },
  { singular: "second", plural: "seconds" },
  { singular: "moment", plural: "moments" },
  { singular: "phase", plural: "phases" },
  { singular: "stage", plural: "stages" },
  { singular: "step", plural: "steps" },
  { singular: "level", plural: "levels" },
  { singular: "grade", plural: "grades" },
];

export const wordBankC = [
  { singular: "reptile", plural: "reptiles" },
  { singular: "piece of furniture", plural: "furniture" },
  { singular: "vegetable", plural: "vegetables" },
  { singular: "insect", plural: "insects" },
  { singular: "building", plural: "buildings" },
  { singular: "fish", plural: "fishes" },
  { singular: "item of clothing", plural: "clothes" },
  { singular: "food", plural: "foods" },
  { singular: "drink", plural: "drinks" },
  { singular: "game", plural: "games" },
  { singular: "continent", plural: "continents" },
  { singular: "country", plural: "countries" },
  { singular: "city", plural: "cities" },
  { singular: "village", plural: "villages" },
  { singular: "town", plural: "towns" },
  { singular: "river", plural: "rivers" },
  { singular: "lake", plural: "lakes" },
  { singular: "mountain", plural: "mountains" },
  { singular: "valley", plural: "valleys" },
  { singular: "forest", plural: "forests" },
  { singular: "desert", plural: "deserts" },
  { singular: "island", plural: "islands" },
  { singular: "peninsula", plural: "peninsulas" },
  { singular: "ocean", plural: "oceans" },
  { singular: "sea", plural: "seas" },
  { singular: "bay", plural: "bays" },
  { singular: "gulf", plural: "gulfs" },
  { singular: "plateau", plural: "plateaus" },
  { singular: "plain", plural: "plains" },
  { singular: "hill", plural: "hills" },
  { singular: "road", plural: "roads" },
  { singular: "street", plural: "streets" },
  { singular: "avenue", plural: "avenues" },
  { singular: "bridge", plural: "bridges" },
  { singular: "tunnel", plural: "tunnels" },
  { singular: "airport", plural: "airports" },
  { singular: "station", plural: "stations" },
  { singular: "port", plural: "ports" },
  { singular: "harbor", plural: "harbors" },
  { singular: "market", plural: "markets" },
  { singular: "shop", plural: "shops" },
  { singular: "store", plural: "stores" },
  { singular: "mall", plural: "malls" },
  { singular: "theater", plural: "theaters" },
  { singular: "cinema", plural: "cinemas" },
  { singular: "museum", plural: "museums" },
  { singular: "gallery", plural: "galleries" },
];

export const dataset = [
  {
    premise: "All A are B.",
    questions: [
      {
        text: "All B are A.",
        correct: false,
        explanation:
          "Just because all A are B does not mean all B are A. For example, all cats are mammals, but not all mammals are cats.",
        keyTakeaway: "If all A are B, it does not mean all B are A.",
      },
      {
        text: "Some B are not A.",
        correct: false,
        explanation:
          "If all A are B, it is possible that all B are A, but not necessary. There could be B that are not A, but this is not guaranteed.",
        keyTakeaway: "All A are B does not guarantee that some B are not A.",
      },
      {
        text: "At least one B is A.",
        correct: true,
        explanation:
          "If all A are B, then at least one B must be an A, since there is at least one A.",
        keyTakeaway: "All A are B implies at least one B is A.",
      },
      {
        text: "If something is not a A, then it is not a B.",
        correct: false,
        explanation:
          "If something is not A, it could still be B. For example, a dog is not a cat, but it is still a mammal.",
        keyTakeaway: "Not A does not mean not B.",
      },
      {
        text: "If something is not a B, then it is not a A.",
        correct: true,
        explanation: "If all A are B, then anything that is not B cannot be A.",
        keyTakeaway:
          "Not B implies not A if all A are B. This is the contrapositive.",
      },
    ],
  },
  {
    premise: "Some A are B.",
    questions: [
      {
        text: "At least one B is a A.",
        correct: true,
        explanation:
          "If some A are B, then at least one B must be an A, since there is at least one A that is B.",
        keyTakeaway: "Some A are B implies at least one B is a A.",
      },
      {
        text: "At least one A is not a B.",
        correct: true,
        explanation:
          "If some A are B, it is possible that not all A are B, so at least one A may not be a B.",
        keyTakeaway: "Some A are B allows for some A not being B.",
      },
      {
        text: "All B are A.",
        correct: false,
        explanation:
          "Some A are B does not mean all B are A. For example, some cats are black, but not all black things are cats.",
        keyTakeaway: "Some A are B does not mean all B are A.",
      },
      {
        text: "It is possible that all B are A.",
        correct: true,
        explanation:
          "If some A are B, it is possible (but not necessary) that all B are A.",
        keyTakeaway:
          "Some A are B allows for all B being A, but does not require it.",
      },
    ],
  },
  {
    premise: "No A are B.",
    questions: [
      {
        text: "If something is a B, it cannot be a A.",
        correct: true,
        explanation: "If no A are B, then being a B excludes being an A.",
        keyTakeaway: "No A are B means B cannot be A.",
      },
      {
        text: "If something is a A, it cannot be a B.",
        correct: true,
        explanation: "If no A are B, then being an A excludes being a B.",
        keyTakeaway: "No A are B means A cannot be B.",
      },
    ],
  },
  {
    premise: "A must be either B or C.",
    questions: [
      {
        text: "A cannot be both B and C simultaneously.",
        correct: true,
        explanation:
          "If A must be either B or C, then A cannot be both at the same time.",
        keyTakeaway: "Either/or excludes both.",
      },
      {
        text: "A cannot be neither B nor C.",
        correct: true,
        explanation:
          "If A must be either B or C, then A must be one or the other, not neither.",
        keyTakeaway: "Either/or means A must be B or C.",
      },
    ],
  },
];
